'use strict';
const fullName = 'Mahdieh Maleki';
const isCool = true;
const totalPets = 1;
const empty = null;
let nothing;
console.log('value of fullName is: ', fullName);
console.log('value of isCool is: ', isCool);
console.log('value of totalPets is: ', totalPets);
console.log('type of fullName is: ', typeof fullName);
console.log('type of isCool is: ', typeof isCool);
console.log('type of totalPets is: ', typeof totalPets);
console.log('value of empty is: ', empty);
console.log('type of empty is: ', typeof empty);
console.log('value of nothing is: ', nothing);
console.log('type of nothing is: ', typeof nothing);
