'use strict';
const colors = ['red', 'white', 'blue'];
console.log('Value of colors[0]: ', colors[0]);
console.log('Value of colors[1]: ', colors[1]);
console.log('Value of colors[2]: ', colors[2]);
const interpolatedString1 = `America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(interpolatedString1);
colors[2] = 'green';
const interpolatedString2 = `Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(interpolatedString2);
console.log('Value of colors: ', colors);
console.log('Type of colors: ', typeof colors);
const students = ['Madia', 'Philip', 'Shea', 'Devin'];
const numberOfStudents = students.length;
const interpolatedString3 = `There are ${numberOfStudents} students in the class.`;
console.log(interpolatedString3);
const lastIndex = students.length - 1;
const lastStudent = students[lastIndex];
const interpolatedString4 = `The last Student in the array is ${lastStudent}.`;
console.log(interpolatedString4);
console.log('Value of Students: ', students);
console.log('Type of students: ', typeof students);
