'use strict';
const width = 4;
const height = 5;
const area = width * height;
console.log('Value of area is: ', area);
console.log('Type of area is: ', typeof area);
const bill = 250;
const payment = 300;
const change = payment - bill;
console.log('Value of change is: ', change);
console.log('Type of change is: ', typeof change);
const quizzes = 89;
const midterm = 95;
const final = 92;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade is: ', grade);
console.log('Type of grade is: ', typeof grade);
const firstName = 'Mahdieh';
const lastName = 'Maleki';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName is: ', fullName);
console.log('Type of fullName is: ', typeof fullName);
const pH = 8;
const isAcidic = pH <= 7;
console.log('Value of isAcidic is: ', isAcidic);
console.log('Type of isAcidic is: ', typeof isAcidic);
const headCount = 290;
const isSparta = headCount === 300;
console.log('Value of isSparta is: ', isSparta);
console.log('Type of isSparta is: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT!';
console.log('Value of motto is: ', motto);
console.log('Type of motto is: ', typeof motto);
